version: '3'

volumes:
  mysql-data:

services:
  app:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./scraping:/var/www/html
    links:
      - mysql


  adminer:
    image: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: mysql
    ports: 
      - 8001:8080
    links:
      - mysql

  mailcatcher:
    image: jeanberu/mailcatcher
    ports:
      - 1025:1025
      - 8002:1080
  
  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraping
    volumes: 
      - mysql-data:/var/lib/mysql

