/:
    controller: UserController
    method: logIn
    autorization: null
login:
    controller: UserController
    method: logIn
    autorization: null
logout:
    controller: UserController
    method: logout
    autorization: null
signup:
    controller: UserController
    method: signup
    autorization: null
recovery-account:
    controller: UserController
    method: recoveryAccount
    autorization: null
change-password:
    controller: UserController
    method: changePassword
    autorization: null
404:
    controller: ErrorController
    method: error404
    autorization: null
extraction/new:
    controller: ExtractionController
    method: create
    autorization: admin
dashboard:
    controller: ExtractionController
    method: getList
    autorization: admin
extraction/(\d+):
    controller: ExtractionController
    method: getOne
    autorization: admin
extraction/(\d+)/delete:
    controller: ExtractionController
    method: delete
    autorization: admin
extraction/(\d+)/update:
    controller: ExtractionController
    method: update
    autorization: admin
my-account:
    controller: UserController
    method: update
    autorization: admin
extraction/(\d+)/historic/(\d+):
    controller: HistoricController
    method: getOne
    autorization: admin
extraction/(\d+)/historic/(\d+)/delete:
    controller: HistoricController
    method: deleteOne
    autorization: admin
extraction/(\d+)/historic/delete:
    controller: HistoricController
    method: deleteAll
    autorization: admin
extraction/(\d+)/historic/new:
    controller: HistoricController
    method: create
    autorization: admin
